### ISSUE TITLE
Build exception when deploying on 

### ISSUE THREAD

**Issue by hellgheast** [pushbit/sprockets-android#10]
Actually I try to compile (C1) my program using this library 
using the gradle compile (C2) instructions and when i build on my computer i get no errors but when it comes to deploy it on a smartphone i get these errors (F1).

Any suggestion ?

C1 : 
JDK : jdk1.8.0_11  Android Studio : 1.4.1 SDK : Default directory

C2 :
    compile 'com.android.support:appcompat-v7:23.1.1'
    compile 'com.android.support:design:23.1.1'
    compile 'com.google.android.gms:play-services:8.3.0'
    compile 'net.sf.sprockets:sprockets-android:3.0.0'
    compile 'com.google.android.gms:play-services-ads:8.3.0'
    compile 'com.google.android.gms:play-services-identity:8.3.0'
    compile 'com.google.android.gms:play-services-gcm:8.3.0'

[F1.txt](https://github.com/pushbit/sprockets-android/files/40963/F1.txt)

**Comment by pushbit** [comment]
The crux of the message seems to be, "This class was probably produced by a compiler that did not target the modern .class file format. The recommended solution is to recompile the class from source, using an up-to-date compiler and without specifying any '-target' type options."

How exactly are you deploying?  Are you just clicking the 'Run' button in Android Studio?  Does the relevent `buildTypes` child have `minifyEnabled true`?  Perhaps try removing the `play-services` dependency (which I believe includes all of them) and only use the individual modules (like `play-services-ads`).  Googling the above error message seems to indicate that it could be caused by duplicate jars or jars with `java.` or `javax.` classes.

**Comment by hellgheast** [comment]
Hello,
Yes I deploy it on click on the run button on Android Studio.
I added to the buildTypes release & debug the minifyEnabled true instruction.
I use now only these two packages (C1)

One curious thing is that Android Studio is automatically taking the com.google.android.gms.location.places.Places instead of yours when i don't do an explicit select of the package.

With your advice (S1) i solved on using individuals module,and after name explicitly if i use the Places of your library of the one the Google Play Services,so the compilator don't see duplicate java classes.

C1:
    compile 'com.google.android.gms:play-services-maps:8.3.0'
    compile 'com.google.android.gms:play-services-location:8.3.0'

S1 : Choose individual modules and name the entire package when you use classes with the same name.

Example:
* API Sprockets-Android
```java
mResp=Places.nearbySearch(net.sf.sprockets.google.Places.Params.create()
              .latitude(mLastLocation.getLatitude())
              .longitude(mLastLocation.getLongitude())
              .radius(1000)
              .addTypes("restaurant"));
```
* API Google Play Services
```java
 mGoogleApiClient = new GoogleApiClient
                .Builder(this)
                .addApi(com.google.android.gms.location.places.Places.GEO_DATA_API)
                .addApi(LocationServices.API) // On rajoute le service de localisation
                .addConnectionCallbacks(this)
                .addOnConnectionFailedListener(this)
                .build();
```

**Comment by pushbit** [comment]
Are you able to deploy the app successfully now?

**Comment by hellgheast** [comment]
Yes,without problem.
