### ISSUE TITLE
android studio gives error on compiling sprockets library

### ISSUE THREAD

**Issue by Aditya21196** [pushbit/sprockets-android#12]
Whenever I try to compile the sprockets library, my app apk is unable to build. Then again if I remove the following from my app build.gradle:

>compile 'net.sf.sprockets:sprockets-android:3.0.0'

the apk gets built without error. What do you suggest I should do?

**Comment by pushbit** [comment]
What is the error?

**Comment by pushbit** [comment]
It seems that the latest version of the Gradle plug-in requires some additional build configuration.  I have updated the [Install][1] instructions so that step 2 is now required and I inserted step 3.  Please let me know if that resolves your build issue.

[1]: https://github.com/pushbit/sprockets-android#install

**Comment by Aditya21196** [comment]
The issue was resolved. It was not given in instructions that jar file also needs to be added from project configurations so just I was confused how to configure the library.
