### ISSUE TITLE
Debug minify should not be true

### ISSUE THREAD

**Issue by danielgomezrico** [pushbit/sprockets-android#9]
Hi

The lib is awesome, it works nice but having `minifyEnabled true` for debug is a complete pain, it takes so much on every build that I had to remove this.

Maybe splitting the library in small libraries or something may remove this...

**Comment by pushbit** [comment]
The last time I tried to build without `minifyEnabled`, I exceeded the DEX method limit.  But in the next version of Sprockets I am changing the `play-services` dependency from the main module to only the sub-modules that are needed.  Now I am able to build without `minifyEnabled`.  So I will remove this from the install instructions and include it as a note for release builds.

Though interestingly, my debug builds are significantly faster with `minifyEnabled` (10s vs. 45s).  I guess because the code stripping runs decently fast and it has much less to package.  Just out of curiosity, what are your timings like?

**Comment by danielgomezrico** [comment]
You are right, it takes 30 s less with `minifyEnabled true`.
I was thinking like one process less to execute (minify) and then faster builds, but no.

I don´t know then what is killing my build time, it takes 1 minute with minify true.

**Comment by pushbit** [comment]
Maybe try setting `org.gradle.daemon=true` in `gradle.properties`.  Gradle build time seems to be a frequent complaint, and the Android tools team is working to improve the performance.  Of course a fast processor, lots of RAM, and a fast SSD drive help. :)

**Comment by danielgomezrico** [comment]
yeah, now I cant live without an SSD :+1:.
